/**:
  ros__parameters:
    tolerance_m: 0.7
    voxel_leaf_size_m: 0.3
    min_points_per_voxel: 1
    min_points_per_cluster: 10
    max_voxels_per_cluster: 800
    large_cluster_voxel_count_threshold: 65
    large_cluster_max_points_per_voxel: 10
    use_height: false
