/**:
  ros__parameters:
    trt_precision: fp16
    cloud_capacity: 2000000
    onnx_path: "$(var model_path)/$(var model_name).onnx"
    runtime_mode: active
    period: 5.0
    queue_size: 5
    ego_box: [-1.53, -1.15, -0.1, 5.72, 1.15, 3.1]
    input:
      cloud_topics: ["/sensing/lidar/concatenated/pointcloud"]
      image_topics:
        [
          "/sensing/camera/camera8/image_raw",
        ]
      approx_deltas: [0.1]
      miscalibration_confidence_thresholds: [0.0]
      already_rectified: [false]
    prerequisite:
      linear_velocity_check:
        enabled: true
        source: twist_with_cov_stamped
        threshold: 3.0
        timeout: 1.0
      angular_velocity_check:
        enabled: true
        source: twist_with_cov_stamped
        threshold: 0.1745  # 10 degrees in radians
        timeout: 1.0
      objects_check:
        enabled: true
        source: predicted_objects
        threshold: 100
        timeout: 1.0
