/**:
  ros__parameters:
    initial_tracker:
      car: "pass_through_tracker"
      truck: "pass_through_tracker"
      bus: "pass_through_tracker"
      trailer: "pass_through_tracker"
      pedestrian: "pass_through_tracker"
      bicycle: "pass_through_tracker"
      motorcycle: "pass_through_tracker"
